# Generated by Django 4.1.2 on 2022-10-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnJapApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunpo',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bunpo',
            name='examples',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
