# Generated by Django 4.1.2 on 2022-10-20 10:25

from django.db import migrations, models
import learnJapApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('learnJapApp', '0002_bunpo_level_alter_bunpo_examples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunpo',
            name='examples',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[learnJapApp.models.exmapleValidator]),
        ),
    ]
