# Generated by Django 4.0.3 on 2022-10-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnJapApp', '0004_bunpo_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunpo',
            name='connection',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
