# Generated by Django 4.1.2 on 2022-10-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnJapApp', '0005_alter_bunpo_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunpo',
            name='connection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
