# Generated by Django 4.1.2 on 2022-10-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnJapApp', '0006_alter_bunpo_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='bunpoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(max_length=255)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('questionContent', models.CharField(max_length=255)),
                ('answerType', models.CharField(max_length=255)),
                ('questionAbout', models.ManyToManyField(blank=True, related_name='question', to='learnJapApp.bunpo')),
            ],
        ),
    ]
