# Generated by Django 4.1.2 on 2022-10-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnJapApp', '0007_bunpoquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunpoquestion',
            name='questionAbout',
        ),
        migrations.AddField(
            model_name='bunpo',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='bunpo', to='learnJapApp.bunpoquestion'),
        ),
    ]
