# Generated by Django 4.1.2 on 2022-10-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnJapApp', '0010_alter_bunpo_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunpo',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='bunpo', to='learnJapApp.bunpoquestion'),
        ),
    ]
