# Generated by Django 4.1.2 on 2022-10-22 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnJapApp', '0012_alter_bunpoquestion_questiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunpoquestion',
            name='answerType',
        ),
        migrations.AddField(
            model_name='bunpoquestion',
            name='questioningAbout',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='learnJapApp.bunpo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bunpoquestion',
            name='questionType',
            field=models.CharField(choices=[('Multiple Choice', 'Multiple choice'), ('Link', 'Link')], default='None', max_length=255),
        ),
    ]
