# Generated by Django 4.1.2 on 2022-10-22 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnJapApp', '0014_remove_bunpoquestion_questioningabout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunpoquestion',
            name='questioningAbout',
        ),
        migrations.AddField(
            model_name='bunpoquestion',
            name='questioningAbout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='learnJapApp.bunpo'),
        ),
    ]
