# Generated by Django 4.1.2 on 2022-10-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnJapApp', '0015_remove_bunpoquestion_questioningabout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunpoquestion',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
